### PR TITLE
Migrate to dbus-next

### LINKED ISSUE #1: Wrong types for some properties
Using the latest version,

```
(playerctl:16525): GLib-GIO-WARNING **: Received property Rate with type y does not match expected type d in the expected interface

(playerctl:16525): GLib-GIO-WARNING **: Received property Volume with type y does not match expected type d in the expected interface

(playerctl:16525): GLib-GIO-WARNING **: Received property Position with type y does not match expected type x in the expected interface

(playerctl:16525): GLib-GIO-WARNING **: Received property MinimumRate with type y does not match expected type d in the expected interface

(playerctl:16525): GLib-GIO-WARNING **: Received property MaximumRate with type y does not match expected type d in the expected interface
```

### LINKED ISSUE #6: Use pure JS node-dbus ?
If all required features are there, I think it would be nice to switch into pure JS version to improve portability.

### LINKED ISSUE #13: CanGoPrevious & CanGoNext variable updating but mpris is not
When setting the value after the initial value is set, the values change but the mpris widget doesn't change anymore.

### PR DESCRIPTION
**Pull request by acrisci**
Migration to dbus-next (a fork of dbus-native) is a rewrite, but fixes
some outstanding bugs in the project related to variant types.

The project is now transpiled to use the experimental decorator feature
that will be available in the language at some later time. gulpfile.js
contains build instructions. Build with `npm run build`. The dist/
folder contains what will be published on npm.

Interfaces are implemented as classes with decorators specifying the
properties of the member that is exported on the bus.

Update examples and add a new tracklist example.

Other bugfixes may have been a side effect of the rewrite.

fixes #1
fixes #6
fixes #13

### CODE REVIEW

**Comment by emersion** [comment]
Any news about this?

**Comment by sidorares** [comment]
@emersion sorry still didn't have any free time, maybe over holiday period

**Comment by emersion** [comment]
No worries, and thanks for your hard work on dbus-native!

**Comment by martpie** [comment]
This would be absolutely awesome to have `mpris-service` based on `node-dbus-next` :D

**Comment by acrisci** [comment]
The last problem to solve is to get my required node engine version down to about 6.3 and then I can go about my glorious mission to fix javascript media players.

**Comment by acrisci** [comment]
Hey @emersion this is ready for review.

Run `npm run build` to build the project to the `dist` folder.

Run tests with `npm run test`.

Build docs to the `doc` folder with `npm run doc`

**Pull request merged**
